services:
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 2s
      timeout: 3s
      retries: 10
  api:
    build: .
    entrypoint: ./entrypoint.sh
    restart: always
    volumes:
      - type: bind
        source: .
        target: /home/app/www
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://appuser:P4ssWD@db:5432/evo
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pg_data:
